- block: # runs on master nodes except the first node in this group
  - name: drain master nodes
    shell: kubectl drain {{ item }} --delete-emptydir-data --force --grace-period 0 --timeout 30s
    ignore_errors: true
    loop: "{{ groups['kube_control_plane'][1:] }}" 

  - name: run kubeadm reset worker nodes
    shell: kubeadm reset -f 
    loop: "{{ groups['kube_control_plane'][1:] }}" 
      
  - name: remove the rest files and directories which kubeadm does not delete
    file:
      path: "{{ item }}"
      state: absent
    loop:
      - /etc/kubernetes
      - /etc/cni/.net.d
      - /var/lib/kubelet
      - /var/lib/etcd
    loop: "{{ groups['kube_control_plane'][1:] }}" 

  - name: stop and disable kubelet on worker nodes
    systemd:
      name: kubelet
      state: stopped
      enabled: no
    loop: "{{ groups['kube_control_plane'][1:] }}" 

  - name: Remove Kubernetes components from worker nodes
    package:
      name:
        - kubeadm
        - kubelet
        - kubectl
      state: absent
    loop: "{{ groups['kube_control_plane'][1:] }}" 
  
  - name: delete master nodes from cluster
    shell: kubectl delete node {{ item }} 
    loop: "{{ groups['kube_control_plane'][1:] }}" 
      
  when: inventory_hostname == groups['kube_control_plane'][0]   
