- hosts: k8s_cluster
  tasks: 
    - name: pre-flight-checks | check if nodes ram >= 2GB
      fail:
        msg: "insufficient ram: {{ ansible_memory_mb.real.total }}"
      when: ansible_memory_mb.real.total < 2048 
      ignore_errors: true


- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: pre-flight-checks | check if hostnames are unique
      vars: 
        node_names: "{{ groups['all'] | map('extract', hostvars, 'ansible_hostname') }}"
        node_count: "{{ node_names | length }}"
        unique_host_names_count: "{{ node_names | unique | length }}"
      assert:
        that: 
          - unique_host_names_count == node_count
        fail_msg: "hostnames are not unique:  {{ node_names }}"

    - name: pre-flight-checks | check if nodes mac-address are unique
      vars: 
        nodes_mac: "{{ groups['all'] | map('extract', hostvars, 'ansible_default_ipv4') | map(attribute='macaddress') }}"
        macs_count: "{{ nodes_mac | length }}"
        unique_macs_count: "{{ nodes_mac | unique | length }}"
      assert:
        that: 
          - unique_macs_count == macs_count
        fail_msg: "mac-addresses are not unique:  {{ nodes_mac }}"

# - name: pre-flight-checks | check if swap is disabled

# - name: pre-flight-checks | check network adapters
  
# - name: pre-flight-checks | check if required ports are open 
