---
- hosts: kube_control_plane
  gather_facts: false
  become: true
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  tasks: 
    
    - block:
      - name: join admin nodes | download certs on controller machine
        synchronize:
          src: /etc/kubernetes/pki/
          dest: /tmp/pki/
          mode: pull
          
      - name: join admin nodes | create token
        command: kubeadm token create --print-join-command
        register: join_command
      when: inventory_hostname == groups['kube_control_plane'][0]
      any_errors_fatal: true
         
    - block:     
      - name: join admin nodes | create /etc/kubernetes/pki directory
        file: 
          path: /etc/kubernetes/pki
          state: directory
 
      when: inventory_hostname != groups['kube_control_plane'][0]
      any_errors_fatal: true

