---
- hosts: kube_control_plane
  gather_facts: false
  become: true
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  tasks: 
    
    - block:
      - name: join admin nodes | download certs on controller machine
        synchronize:
          src: /etc/kubernetes/pki/
          dest: /tmp/pki/
          mode: pull
          
      - name: join admin nodes | create token
        command: kubeadm token create --print-join-command
        register: join_command
      when: inventory_hostname == groups['kube_control_plane'][0]
      any_errors_fatal: true
         
    - block:     
      - name: join admin nodes | create /etc/kubernetes/pki directory
        file: 
          path: /etc/kubernetes/pki
          state: directory
 
      - name: join admin nodes | copy certs to other admin nodes
        synchronize: 
          src: /tmp/pki/
          dest: "/etc/kubernetes/pki/"
          mode: push

      - name: join admin nodes | run join command
        command: "{{ hostvars[ groups['kube_control_plane'][0] ].join_command.stdout }} --control-plane --ignore-preflight-errors NumCPU"
        when: inventory_hostname != groups['kube_control_plane'][0]
      when: inventory_hostname != groups['kube_control_plane'][0]
      any_errors_fatal: true

- hosts: localhost
  connection: local
  gather_facts: false
  become: true
  tasks: 
    - name: join admin nodes | remove cert files from controller node
      file:
        path: /tmp/pki/
        state: absent
