---
- hosts: kube_control_plane
  gather_facts: false
  become: true
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  tasks: 
    
    - block:
      - name: join-admin-nodes | run kubeadm upload certs phase to get certificate-key
        register: CERT_KEY
        shell: kubeadm init phase upload-certs --upload-certs | awk 'NR==3'

      - name: join-admin-nodes | generate join commands
        register: initial_join_command
        shell: "kubeadm token create --print-join-command --certificate-key {{CERT_KEY.stdout}}"
        
      - name: join-admin-nodes | modify join commands
        set_fact:
          join_command: "{{ initial_join_command.stdout }} --ignore-preflight-errors NumCPU"
      when: inventory_hostname == groups['kube_control_plane'][0]
        

    - block: 
      - name: join-admin-nodes | add VIP dns record to /etc/hosts
        lineinfile:
          path: /etc/hosts
          line: "{{ hostvars[ groups['kube_control_plane'][0] ].ansible_host }} {{ VIP_DNS_RECORD }}"
          state: present
        
      - name: join-admin-nodes | copy kube-vip conf file to /etc/kubernetes/manifests/
        copy:
          src: ../roles/install-kubeadm/files/kube-vip.yaml
          dest: /etc/kubernetes/manifests/kube-vip.yaml
          mode: 0600

      - name: join-admin-nodes | run join command
        shell: "{{ hostvars[ groups['kube_control_plane'][0] ].join_command }}"

      when: inventory_hostname != groups['kube_control_plane'][0]
