---
- hosts: kube_control_plane[0]
  gather_facts: false
  become: true
  tasks:
    - name: join admin nodes | create token
      command: kubeadm token create --print-join-command
      register: join_command

- hosts: kube_control_plane[1:]
  gather_facts: false
  become: true
  tasks:
    - name: join admin nodes | run join command
      command: "{{ hostvars[ groups['kube_control_plane'][0] ].join_command.stdout }} --control-plane"

