---
- hosts: kube_control_plane
  gather_facts: false
  become: true
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  tasks: 
    
    - block:
      - name: join-admin-nodes | run kubeadm upload certs phase to get certificate-key
        register: CERT_KEY
        shell: kubeadm init phase upload-certs --upload-certs | awk 'NR==3'

      when: inventory_hostname == groups['kube_control_plane'][0]
        

