--- 
APISERVER_PORT: 6443
  
# kubeadm init \
#   --pod-network-cidr 10.244.0.0/16 \
#   --service-cidr 10.96.0.0/12 \
#   --apiserver-advertise-address 10.0.0.1 \
#   --apiserver-bind-port 8443 \
#   --node-name master-node
