---

- name: restart-containerd
  service:
    name: containerd
    state: restarted

- name: restart_systemd_resolved
  service: 
    name: systemd-resolved
    state: restarted

- name: restart-docker-service
  service:
    name: docker
    state: restarted

- name: restart-cri-dockerd-service
  service:
    name: cri-docker
    state: restarted
