---
- name: modify swap configs to disabling it permanently
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  when: ansible_swaptotal_mb > 0

- name: disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
