- name: download cri-dockerd package
  get_url: 
    url: https://github.com/Mirantis/cri-dockerd/releases/download/v0.3.14/cri-dockerd_0.3.14.3-0.ubuntu-jammy_amd64.deb
    dest: ~/cri-dockerd

- name: install cri-dockerd
  apt:
    deb: ~/cri-dockerd
  notify: restart-cri-dockerd-service
