- block:
     
    - name: install calico | download tigera.yaml
      get_url: 
        url: https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/tigera-operator.yaml
        dest: ~/tigera.yaml
        mode: 0644
          
    - name: install calico | install tigera operator
      k8s:
        state: present
        src: ~/tigera.yaml
      
    - name: install calico | download calico.yaml
      get_url: 
        url: https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/custom-resources.yaml
        dest: ~/calico.yaml
        mode: 0644
      
    - name: install calico | apply calico.yaml
      k8s: 
        state: present
        src: ~/calico.yaml
      
  when: inventory_hostname == groups['kube_control_plane'][0]
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
 
