--- 
- name: install required packages | install pre-requisits packages
  apt:
    name: 
      - apt-transport-https 
      - ca-certificates 
      - curl 
      - gpg
    state: present
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
    
- name: install required packages | add Kubernetes repository signing key
  apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
    state: present
    keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: add Kubernetes repository to APT
  apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /'
    state: present
      
- name: install required packages | install containerd kubeadm kubelet kubectl
  apt:
    name:
      - containerd=1.7.12-0ubuntu4
      - kubelet=1.30.0-1.1
      - kubeadm=1.30.0-1.1
      - kubectl=1.30.0-1.1
    state: present
    update_cache: true
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: install required packages | create /etc/containerd
  file:
    path: /etc/containerd
    state: directory

- name: install required packages | config containerd 
  copy: 
    src: ../files/containerd-config.toml
    dest: /etc/containerd/config.toml
    mode: 0644
  notify: restart-containerd
