--- 
- name: install pre-requisits packages
  apt:
    name: 
      - apt-transport-https 
      - ca-certificates 
      - curl 
      - gpg
    state: present
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
    
- name: add Kubernetes repository signing key
  apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
    state: present
    keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: add Kubernetes repository to APT
  apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /'
    state: present
      
- name: install containerd kubeadm kubelet kubectl
  apt:
    name:
      - kubelet=1.30.0-1.1
      - kubeadm=1.30.0-1.1
      - kubectl=1.30.0-1.1
    state: present
    update_cache: true
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

