- name: install containerd | install containerd using apt 
  apt: 
    name: containerd=1.7.12-0ubuntu4
    update_cache: true
      
- name: install containerd | config containerd 
  copy: 
    src: ../files/containerd-config.toml
    dest: /etc/containerd/config.toml
    mode: 0644
  notify: restart-containerd
