- name: install containerd | Create /etc/apt/keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755
    owner: root
    group: root

- name: install containerd | Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: 0644

- name: install containerd | Set permissions for Docker GPG key y
  file:
    path: /etc/apt/keyrings/docker.asc
    mode: 0644

- name: install containerd | Add Docker repository to APT sources
  ansible.builtin.blockinfile:
    path: /etc/apt/sources.list.d/docker.list
    create: yes
    block: |
      deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

- name: install containerd | install containerd.io
  apt: 
    update_cache: yes
    name: containerd.io=1.6.31-1
    state: present

- name: install containerd | create /etc/containerd directory
  file: 
    path: /etc/containerd
    state: directory
    mode: 0755

- name: install containerd | config containerd 
  copy: 
    src: ../files/coredns-config.yml
    dest: /etc/containerd/config.toml
    mode: 0644
  notify: restart-containerd
