--- 
- name: install required packages | install pre-requisits packages
  apt:
    name: 
      - rsync=3.2.7-1ubuntu1
      - apt-transport-https 
      - ca-certificates 
      - curl 
      - gpg
      - python3-pip=24.0+dfsg-1ubuntu1  
    state: present
    update_cache: true
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
    
- name: install required packages | install ansible k8s module dependencies 
  pip: 
    name: 
      - kubernetes==29.0.0
      # - pyyaml==6.0
      # - jsonpatch==1.32
    state: present
    extra_args: --break-system-packages
  when: inventory_hostname in groups['kube_control_plane']

- name: install required packages | add Kubernetes repository signing key
  apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
    state: present
    keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: add Kubernetes repository to APT
  apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /'
    state: present

- name: install required packages | install containerd kubeadm kubelet kubectl
  apt:
    name:
      - kubelet=1.30.0-1.1
      - kubeadm=1.30.0-1.1
      - kubectl=1.30.0-1.1
    state: present
    update_cache: true
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
