- name: install required packages | install containerd
  apt:
    name:
      - containerd=1.7.12-0ubuntu4
    state: present
    update_cache: true
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: install required packages | create /etc/containerd
  file:
    path: /etc/containerd
    state: directory

- name: install required packages | config containerd 
  copy: 
    src: ../files/containerd-config.toml
    dest: /etc/containerd/config.toml
    mode: 0644
  notify: restart-containerd
