---

- name: set hostnames in /etc/hosts
  become: true
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item]['ansible_host'] }} {{ hostvars[item]['ansible_nodename'] }}"
    state: present
  loop: "{{ groups['all'] | difference([inventory_hostname]) }}"

- name: set KUBECONFIG env var
  become: true
  lineinfile:
    path: /root/.bashrc
    line: "export KUBECONFIG=/etc/kubernetes/admin.conf"
  when: inventory_hostname in groups['kube_control_plane']


