--- 

- name: run kubeadm init command
  shell: |
    kubeadm init \
      --control-plane-endpoint "{{ ansible_host:APISERVER_PORT }}" \
      --pod-network-cidr 192.168.0.0/16                            \
      --upload-certs                                               \   
      --ignore-preflight-errors NumCPU                           
  run_once: true
  when: inventory_hostname in groups['kube_control_plane']
  register: kubeadm-init-result
  

- name: print init result
  var: kubeadm-init-result

- name:

