- name: create kube-apiserver load balancer 

- name: add admin nodes to the load balancer target group
  
- name: copy kubeadm ini config file into the admin1 

- name: run kubeadm init

- name: extract admin and worker tokens

- name: join admin nodes except the admin1

- name: join worker nodes
