
---
- block:
    - name: export kubeadm config path
      become: true
      environment:
        KUBECONFIG: "/etc/kubernetes/admin.conf"

    - name: check if coredns-configmap already applied
      stat: 
        path: /tmp/coredns-configmap.yaml
      register: corednsfile

    - name: get core-dns config map
      become: true
      shell: |
        kubectl get -n kube-system cm coredns -o yaml > /tmp/coredns-configmap.yaml
      when: not corednsfile.stat.exists

    - name: set forward to /etc/systemd/resolved.conf
      become: true
      replace: 
        path: /tmp/coredns-configmap.yaml
        regexp: '^forward \..*'
        replace: 'forward . /etc/systemd/resolved.conf'
      when: not corednsfile.stat.exists

    - name: appy modified core-dns config map
      become: true
      k8s: 
        state: present
        src: /tmp/coredns-configmap.yaml
      when: not corednsfile.stat.exists
  when: inventory_hostname == groups['kube_control_plane'][0]

- name: set hostnames in /etc/hosts
  become: true
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item]['ansible_host'] }} {{ item }}"
    state: present
  loop: "{{ groups['all'] }}"

