--- 
- include_tasks: ./pre-init-ops.yml
- include_tasks: ./install-required-packages.yml
- include_tasks: ./kubeadm-init.yml
- include_tasks: ./post-init-ops.yml
- include_tasks: ./install-calico.yml
