--- 

- name: install kubeadm | disable swap permanently if it is enabled
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  when: ansible_swaptotal_mb > 0

- name: install kubeadm | disable swap if it is enabled
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- include_tasks: ./open-required-ports.yml
- include_tasks: ./install-required-packages.yml
- include_tasks: ./kubeadm-init.yml
# - include_tasks: ./apply-required-configs.yml
# - include_tasks: ./install-calico.yml
# - include_tasks: ./join-admin-nodes.yml
# - include_tasks: ./join-worker-nodes.yml
# - include_tasks: ./run-post-installation-cleanup.yml

