---

- name: set hostnames in /etc/hosts
  vars: 
    ip: "{{ hostvars[item]['ansible_host'] }}" 
    node_name: "{{ hostvars[item]['ansible_nodename'] }}" 
  lineinfile:
    dest: /etc/hosts
    line: "{{ ip }} {{ node_name }}"
    state: present
  loop: "{{ groups['all'] | difference([inventory_hostname]) }}"

- name: set KUBECONFIG env var
  lineinfile:
    path: /root/.bashrc
    line: "export KUBECONFIG=/etc/kubernetes/admin.conf"
  when: inventory_hostname in groups['kube_control_plane'][0]

- name: patch coredns configmap to use /etc/systemd/resolved.conf as dns                                                                                                                                                                                                             
  environment:
    KUBECONFIG: "/etc/kubernetes/admin.conf"
  k8s:                                                                                                                                                                                                                                    
    state: present
    definition: "{{ lookup('file', '/ansible/roles/install-kubeadm/files/coredns-config.yml' | from_yaml )}}"
  when: inventory_hostname == groups['kube_control_plane'][0]
