---

- block: 
  
    - name: post init ops | set KUBECONFIG env var
      lineinfile:
        path: /root/.bashrc
        line: "export KUBECONFIG=/etc/kubernetes/admin.conf"

    - name: post init ops | patch coredns configmap
      environment:
        KUBECONFIG: "/etc/kubernetes/admin.conf"
      k8s:                                                                                                                                                                                                                                    
        state: present
        definition: "{{ lookup('file', '/ansible/roles/install-kubeadm/files/coredns-config.yml' | from_yaml )}}"
          
  when: inventory_hostname == groups['kube_control_plane'][0]
