---
- name: pre-ini-ops | modify swap configs to disabling it permanently
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  when: ansible_swaptotal_mb > 0

- name: pre-ini-ops | disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- include_tasks: ./open-required-ports.yml

- name: pre-init-ops | get host name /etc/hostname
  command: cat /etc/hostname
  register: etc_hostname
  changed_when: false

- name: pre-ini-ops | set unique name for host in /etc/hostname
  shell: echo {{ inventory_hostname }} > /etc/hostname
  when: etc_hostname.stdout != inventory_hostname

- name: pre-init-ops | set unique name for host in env
  lineinfile:
    path: /root/.bashrc
    line: "export hostname={{ inventory_hostname }}"

- name: pre-init-ops | update node name
  set_fact:
    ansible_nodename: "{{ inventory_hostname }}"

- name: pre-ini-ops | update /etc/hosts
  vars: 
    ip: "{{ hostvars[item]['ansible_host'] }}" 
    node_name: "{{ hostvars[item]['ansible_nodename'] }}" 
  lineinfile:
    dest: /etc/hosts
    line: "{{ ip }} {{ node_name }}"
    state: present
  loop: "{{ groups['all'] | difference([inventory_hostname]) }}"

- name: pre-ini-ops | remove extra dns records
  replace:
    path: /etc/systemd/resolved.conf
    regexp: '^(DNS=.*)'
    replace: '# \1'
  notify: restart_systemd_resolved


